### ISSUE TITLE
f-string: unmatched '('

### ISSUE THREAD

**Issue by f-dube** [fcol95/pyfliip#2]
The code bounces back an error when running. After verification, no unmatched '(' was found.

>   File "c:\git\pyfliip_fcol\fliip_register_class.py", line 310
>     f"\t{reg_datetime.strftime("%Y-%m-%d")} - {"New Registration" if just_registered else "Already Registered"}"
>                                 ^
> SyntaxError: f-string: unmatched '('

The total code is:

for reg_datetime, just_registered in registered_return_list:
    if reg_datetime is not None:
        print(
            f"\t{reg_datetime.strftime("%Y-%m-%d")} - {"New Registration" if just_registered else "Already Registered"}"
        )

![image](https://github.com/user-attachments/assets/ee37c675-bf3b-499e-aa5e-63e845b5cbcd)

**Comment by felixFleetZero** [comment]
Fixed with latest commit!
